/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-06-18 02:48:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.votos;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.sample.core.domain.Voto;

public final class votosPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/PC/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("file:/C:/Users/PC/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1750050537180L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.sample.core.domain.Voto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Resultados de Votación</title>\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/Admin.css\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"imagenfondo3\">\r\n");
      out.write("    <h1>Resultados de la Votación</h1>\r\n");
      out.write("    <p style=\"opacity: 0.8;\">Visualizá quién lidera por rol y cómo se distribuyeron los votos</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-principal\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Tabla de resultados -->\r\n");
      out.write("    <div class=\"tabla-votos\">\r\n");
      out.write("        <h2>Tabla de Votos</h2>\r\n");
      out.write("        ");

            List<Voto> votos = (List) request.getAttribute("votos");
        
      out.write("\r\n");
      out.write("        <table>\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>ID Voto</th>\r\n");
      out.write("                    <th>DNI</th>\r\n");
      out.write("                    <th>Presidente</th>\r\n");
      out.write("                    <th>Vicepresidente</th>\r\n");
      out.write("                    <th>Gobernador</th>\r\n");
      out.write("                    <th>Mesa</th>\r\n");
      out.write("                    <th>Fecha</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("            ");
 for (int i = 0; i < votos.size(); i++) { 
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>");
      out.print( votos.get(i).getId_voto() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( votos.get(i).getDNI() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( votos.get(i).getId_presidente() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( votos.get(i).getId_vicepresidente() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( votos.get(i).getId_gobernador() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( votos.get(i).getId_mesa() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( votos.get(i).getFecha_Hora() );
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Gráfico -->\r\n");
      out.write("    <div class=\"graficos\">\r\n");
      out.write("        <h2>Gráfico por Rol</h2>\r\n");
      out.write("        <label for=\"rolSelect\">Seleccioná un rol:</label>\r\n");
      out.write("        <select id=\"rolSelect\">\r\n");
      out.write("            <option value=\"presidente\">Presidente</option>\r\n");
      out.write("            <option value=\"vicepresidente\">Vicepresidente</option>\r\n");
      out.write("            <option value=\"gobernador\">Gobernador</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <canvas id=\"graficoCircular\"></canvas>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Script para cargar gráfico y manejar select -->\r\n");
      out.write("<script>\r\n");
      out.write("    const ctx = document.getElementById('graficoCircular').getContext('2d');\r\n");
      out.write("    const graficoCircular = new Chart(ctx, {\r\n");
      out.write("        type: 'pie',\r\n");
      out.write("        data: {\r\n");
      out.write("            labels: [],\r\n");
      out.write("            datasets: [{\r\n");
      out.write("                label: 'Votos por Partido',\r\n");
      out.write("                data: [],\r\n");
      out.write("                backgroundColor: [],\r\n");
      out.write("                borderColor: [],\r\n");
      out.write("                borderWidth: 1\r\n");
      out.write("            }]\r\n");
      out.write("        },\r\n");
      out.write("        options: {\r\n");
      out.write("            responsive: true,\r\n");
      out.write("            plugins: {\r\n");
      out.write("                legend: {\r\n");
      out.write("                    position: 'bottom'\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    const coloresPorPartido = {\r\n");
      out.write("        'Partido Azul': 'rgba(54, 162, 235, 0.7)',\r\n");
      out.write("        'Partido Rojo': 'rgba(255, 99, 132, 0.7)',\r\n");
      out.write("        'Partido Verde': 'rgba(75, 192, 192, 0.7)'\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    const bordesPorPartido = {\r\n");
      out.write("        'Partido Azul': 'rgba(54, 162, 235, 1)',\r\n");
      out.write("        'Partido Rojo': 'rgba(255, 99, 132, 1)',\r\n");
      out.write("        'Partido Verde': 'rgba(75, 192, 192, 1)'\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    function cargarGraficoPorRol() {\r\n");
      out.write("        const rol = document.getElementById(\"rolSelect\").value;\r\n");
      out.write("        const contextPath = '");
      out.print(request.getContextPath());
      out.write("';\r\n");
      out.write("\r\n");
      out.write("        fetch(contextPath + '/votosPorRol?rol=' + rol)\r\n");
      out.write("            .then(response => {\r\n");
      out.write("                if (!response.ok) throw new Error(\"Error al obtener los datos\");\r\n");
      out.write("                return response.json();\r\n");
      out.write("            })\r\n");
      out.write("            .then(data => {\r\n");
      out.write("                graficoCircular.data.labels = data.labels;\r\n");
      out.write("                graficoCircular.data.datasets[0].data = data.data;\r\n");
      out.write("                graficoCircular.data.datasets[0].backgroundColor = data.labels.map(label => coloresPorPartido[label] || 'rgba(201, 203, 207, 0.7)');\r\n");
      out.write("                graficoCircular.data.datasets[0].borderColor = data.labels.map(label => bordesPorPartido[label] || 'rgba(201, 203, 207, 1)');\r\n");
      out.write("                graficoCircular.update();\r\n");
      out.write("            })\r\n");
      out.write("            .catch(error => console.error(\"Error:\", error));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('rolSelect').addEventListener('change', cargarGraficoPorRol);\r\n");
      out.write("\r\n");
      out.write("    cargarGraficoPorRol(); // carga inicial\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div style=\"text-align: center; margin: 30px 0;\">\r\n");
      out.write("    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/\" class=\"btn-volver\">\r\n");
      out.write("        ⬅ Volver al Inicio\r\n");
      out.write("    </a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
