/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-06-18 07:38:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.seguridad;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class seguridad_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<link rel=\"icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/icon/icon.png\">\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Privacidad y Seguridad del Voto - Sistema Electoral Digital</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/CssPadronElectoral.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"pagina-seguridad\"> ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"titulo-pagina\">\r\n");
      out.write("        <h1>Seguridad</h1>\r\n");
      out.write("        <p id=\"opacity\">Acerca de la seguridad de los votos</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/\" class=\"seleccionar\">Inicio</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/FAQ/FAQ.jsp\" class=\"seleccionar\">FAQ</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/seguridad/seguridad.jsp\" class=\"seleccionar\">Seguridad y Privacidad</a></li>\r\n");
      out.write("            <li class=\"derecha\"><a href=\"#\" id=\"iniciarsesioncheck\">Iniciar Sesión</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"imagenfondo3\">\r\n");
      out.write("    <h2>Privacidad y Seguridad del Voto</h2>\r\n");
      out.write("    <p style=\"opacity: 0.8; font-size: 18px;\">Conocé cómo cuidamos tu identidad y protegemos tu decisión electoral</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<main class=\"container mt-4\">\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section-voto-seguro\">\r\n");
      out.write("        <h3>Principios Fundamentales de Seguridad Electoral</h3>\r\n");
      out.write("        <p class=\"section-description\">Nuestra plataforma está diseñada con los más altos estándares de seguridad y privacidad para garantizar un proceso electoral justo, transparente y confiable.</p>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-group\">\r\n");
      out.write("            <div class=\"card-voto-seguro mb-3\">\r\n");
      out.write("                <div class=\"card-header\"><i class=\"fas fa-lock\"></i> Seguridad del Sistema</div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <p>Implementamos robustas medidas de seguridad informática para garantizar la integridad de cada voto y la protección general de la plataforma.</p>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><i class=\"fas fa-shield-alt\"></i> **Conexiones Cifradas (HTTPS):** Toda la comunicación entre tu navegador y nuestra plataforma está protegida mediante cifrado SSL/TLS, impidiendo que terceros intercepten tus datos.</li>\r\n");
      out.write("                        <li><i class=\"fas fa-user-check\"></i> **Acceso Restringido y Autenticado:** Solo los ciudadanos previamente registrados y validados pueden acceder al sistema de votación, utilizando credenciales seguras para su identificación.</li>\r\n");
      out.write("                        <li><i class=\"fas fa-vote-yea\"></i> **Un Voto por Ciudadano:** Nuestro sistema cuenta con mecanismos estrictos para asegurar que cada votante registrado pueda emitir su voto una única vez, previniendo duplicidades o intentos de fraude.</li>\r\n");
      out.write("                        <li><i class=\"fas fa-server\"></i> **Infraestructura Protegida:** Los servidores que albergan el sistema están resguardados con medidas de seguridad física y lógica, incluyendo firewalls, monitoreo constante y copias de seguridad.</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card-voto-seguro mb-3\">\r\n");
      out.write("                <div class=\"card-header\"><i class=\"fas fa-user-secret\"></i> Protección de Datos Personales y Anonymato</div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <p>Tu privacidad es nuestra prioridad absoluta. Manejamos tus datos personales con la máxima confidencialidad y aseguramos el secreto de tu voto.</p>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><i class=\"fas fa-id-card\"></i> **Uso Exclusivo para Validación:** Tu DNI y nombre completo se utilizan únicamente para verificar tu elegibilidad en el padrón electoral, y no son vinculados a tu elección de voto.</li>\r\n");
      out.write("                        <li><i class=\"fas fa-mask\"></i> **Separación de Identidad y Voto:** Una vez que tu identidad ha sido validada, tu voto es procesado de forma completamente anónima. El sistema registra el voto, no la identidad de quien lo emitió.</li>\r\n");
      out.write("                        <li><i class=\"fas fa-user-slash\"></i> **Confidencialidad Absoluta:** Garantizamos que tu elección de voto es completamente secreta. Ni los administradores del sistema, ni los auditores, ni ningún tercero pueden conocer por quién votaste individualmente.</li>\r\n");
      out.write("                        <li><i class=\"fas fa-gavel\"></i> **Cumplimiento Normativo:** Nuestra plataforma se adhiere estrictamente a las leyes de protección de datos personales vigentes, asegurando un tratamiento legítimo, leal y transparente de tu información.</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card-voto-seguro mb-3\">\r\n");
      out.write("                <div class=\"card-header\"><i class=\"fas fa-lightbulb\"></i> Transparencia y Auditabilidad</div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <p>Creemos en un proceso electoral abierto y verificable para generar plena confianza en los resultados.</p>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><i class=\"fas fa-file-invoice\"></i> **Registro Inmutable de Votos:** Cada voto emitido se registra de manera segura en una base de datos con mecanismos de integridad que impiden su modificación, alteración o eliminación posterior.</li>\r\n");
      out.write("                        <li><i class=\"fas fa-eye\"></i> **Resultados Verificables:** Los datos agregados de los resultados electorales son computados y presentados de manera que permiten su verificación y auditoría por parte de observadores autorizados.</li>\r\n");
      out.write("                        <li><i class=\"fas fa-cogs\"></i> **Auditorías Independientes (Simuladas):** En un entorno real, el código fuente y la infraestructura del sistema serían sometidos a rigurosas auditorías de seguridad por entidades externas e independientes para validar su robustez y ausencia de vulnerabilidades.</li>\r\n");
      out.write("                        <li><i class=\"fas fa-fingerprint\"></i> **Rastreo y Trazabilidad:** Aunque los votos son anónimos, el sistema mantiene registros de auditoría que permiten rastrear eventos sin comprometer la privacidad, lo que facilita la investigación en caso de incidencias.</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"text-center mt-5 mb-5\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/Padron\" class=\"btn btn-primary btn-lg\">¡Votá Ahora de Forma Segura! <i class=\"fas fa-arrow-right\"></i></a>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"mt-5\">\r\n");
      out.write("    <h3>¿Cómo funciona esta plataforma?</h3>\r\n");
      out.write("    <p>Esta aplicación simula un proceso electoral digital. Cada ciudadano registrado puede emitir su voto de forma segura y confidencial.</p>\r\n");
      out.write("    <p>Los administradores gestionan los candidatos, los resultados electorales y la participación, asegurando la equidad del proceso.</p>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <p style=\"font-size: 12px; color: #999;\">Proyecto desarrollado con fines educativos y de demostración. &copy; GuzmanStudios</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
