/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-06-18 07:40:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mesa;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.jasper.tagplugins.jstl.core.Import;
import java.util.*;
import com.sample.core.domain.Mesa;
import com.sample.core.domain.LoginCiudadano;

public final class mesaPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.jasper.tagplugins.jstl.core.Import");
    _jspx_imports_classes.add("com.sample.core.domain.LoginCiudadano");
    _jspx_imports_classes.add("com.sample.core.domain.Mesa");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<link rel=\"icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/icon/icon.png\">\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Listado de Mesas</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/CssPadronElectoral.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Context Path para JS -->\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var contextPath = '");
      out.print(request.getContextPath());
      out.write("';\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Scripts -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/ListarMesa.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/logoutCiudadano.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"titulo-pagina\">\r\n");
      out.write("            <h1>Mesas</h1>\r\n");
      out.write("            <p id=\"opacity\">Bienvenido al padrón! Estas son las mesas disponibles para votar</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"navbar\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/\" class=\"seleccionar\">Inicio</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/FAQ/FAQ.jsp\" class=\"seleccionar\">FAQ</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/seguridad/seguridad.jsp\" class=\"seleccionar\">Seguridad y Privacidad</a></li>\r\n");
      out.write("                           <li class=\"derecha\"><a href=\"#\" id=\"cerrarSesionCiudadano\" class=\"seleccionar\">Cerrar sesión</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container mt-4\">\r\n");
      out.write("        <section class=\"imagenfondo2\">\r\n");
      out.write("            <h2>Listado de Mesas del Distrito</h2>\r\n");
      out.write("            <div class=\"container mt-5\">\r\n");
      out.write("                <h1>Mesas habilitadas en tu distrito:</h1>\r\n");
      out.write("                <div id=\"seleccion\" class=\"d-flex flex-wrap\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-dni\">\r\n");
      out.write("\r\n");
      out.write(" <!-- DNI Card -->\r\n");
      out.write("        <div class=\"dni-card\">\r\n");
      out.write("            <div class=\"dni-header\">\r\n");
      out.write("                <span>República Argentina</span>\r\n");
      out.write("                <span>DNI Electrónico</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"dni-body\">\r\n");
      out.write("                <div class=\"dni-photo\">\r\n");
      out.write("                    <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/profile-picture.png\" alt=\"Foto Ciudadano\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("<div id=\"infoCiudadano\">\r\n");
      out.write("    Cargando datos...\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Importamos el JS externo -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/DNIVirtual.js\"></script>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("        <section class=\"repetidor\" style=\"background-color: #f8f9fa; padding: 40px;\">\r\n");
      out.write("            <div class=\"fila\" style=\"display: flex; gap: 20px; margin-bottom: 30px;\">\r\n");
      out.write("                <!-- Últimas novedades -->\r\n");
      out.write("                <div class=\"columna\" style=\"flex: 1;\">\r\n");
      out.write("                    <h2>📢 Últimas novedades</h2>\r\n");
      out.write("                    <ul style=\"list-style: none; padding: 0;\">\r\n");
      out.write("                        <li><strong>📅 12 de mayo:</strong> Simulador de votación digital habilitado.</li>\r\n");
      out.write("                        <li><strong>🗳️ 5 de mayo:</strong> Nuevos candidatos en distrito centro.</li>\r\n");
      out.write("                        <li><strong>📌 28 de abril:</strong> Cierre padrón provisorio.</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Cómo emitir tu voto -->\r\n");
      out.write("                <div class=\"columna\" style=\"flex: 1;\">\r\n");
      out.write("                    <h2>✅ ¿Cómo emitir tu voto?</h2>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>Ingresá a la sección <strong>Padron</strong>.</li>\r\n");
      out.write("                        <li>Colocá tu DNI y elegí tu mesa.</li>\r\n");
      out.write("                        <li>Seleccioná candidatos y confirmá tu voto.</li>\r\n");
      out.write("                        <li>¡Listo! Tu voto será registrado.</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"fila\" style=\"display: flex; gap: 20px; margin-bottom: 30px;\">\r\n");
      out.write("                <!-- Qué se vota -->\r\n");
      out.write("                <div class=\"columna\" style=\"flex: 1;\">\r\n");
      out.write("                    <h2>🗳️ ¿Qué se vota en esta elección?</h2>\r\n");
      out.write("                    <p>Se elige un representante por distrito. Cada ciudadano puede emitir un solo voto.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Contacto institucional -->\r\n");
      out.write("                <div class=\"columna\" style=\"flex: 1;\">\r\n");
      out.write("                    <h2>📞 Contacto institucional</h2>\r\n");
      out.write("                    <p>Email: elecciones@colegio.edu.ar</p>\r\n");
      out.write("                    <p>Teléfono: (011) 1234-5678</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"fila\" style=\"display: flex; gap: 20px;\">\r\n");
      out.write("                <!-- Citas sobre democracia -->\r\n");
      out.write("                <div class=\"columna\" style=\"flex: 1;\">\r\n");
      out.write("                    <h2>💬 Citas sobre democracia</h2>\r\n");
      out.write("                    <p>“La democracia es la claridad de exponer problemas y resolverlos.” — Enrique Múgica</p>\r\n");
      out.write("                    <p>“Votar es el derecho más poderoso en una democracia.” — Barack Obama</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Preguntas frecuentes -->\r\n");
      out.write("                <div class=\"columna\" style=\"flex: 1;\">\r\n");
      out.write("                    <h2>❓ Preguntas frecuentes</h2>\r\n");
      out.write("                    <p><strong>¿Puedo votar más de una vez?</strong> No.</p>\r\n");
      out.write("                    <p><strong>¿Qué pasa si cierro la página?</strong> Tu voto no será registrado hasta confirmar.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <h3>¿Cómo funciona esta plataforma?</h3>\r\n");
      out.write("        <p>Simula un proceso de elecciones en línea. Cada ciudadano puede emitir un voto válido.</p>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <p style=\"font-size: 12px; color: #999;\">Proyecto educativo. © GuzmanStudios</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
