/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-06-17 10:38:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.FAQ;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FAQ_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("  <title>Preguntas Frecuentes Antes de Votar</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/CssPadronElectoral.css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("        <div class=\"titulo-pagina\">\r\n");
      out.write("            <h1>Menu Principal</h1>\r\n");
      out.write("            <p>Menu principal de la pagina</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"navbar\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/\" class=\"seleccionar\">Inicio</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/FAQ/FAQ.jsp\" class=\"seleccionar\">FAQ</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/seguridad/seguridad.jsp\" class=\"seleccionar\">Seguridad y Privacidad</a></li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"derecha\"><a href=\"#\" class=\"seleccionar\">Iniciar sesión</a></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"faq-container\">\r\n");
      out.write("  <h1>Preguntas Frecuentes Antes de Votar</h1>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Quiénes son los candidatos?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Son las personas que se postulan para cargos públicos en una elección.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Qué experiencia política o profesional tienen?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Depende de cada candidato. Algunos tienen trayectoria, otros son nuevos.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Qué propuestas concretas tienen?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Debés revisar su plan de gobierno para conocerlas.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Qué postura tienen sobre temas importantes?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Depende del candidato. Podés comparar sus declaraciones y propuestas.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Es confiable?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Revisá su historial, denuncias y declaraciones anteriores.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Pertenece a un partido con el que me identifico?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Esto puede ayudarte a decidir tu voto.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Cumple sus promesas?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Compará lo que dijo con lo que hizo antes.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Es un verdadero líder?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Fijate si toma decisiones o es un “títere” del partido.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Con qué personas se rodea?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Su equipo puede decir mucho sobre su gestión futura.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Son viables sus propuestas?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Algunas lo son, otras suenan bien pero no tienen sustento.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Cómo va a financiar lo que propone?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Es importante que lo explique claramente.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿A quién beneficia más?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Revisá si sus políticas ayudan a todos o solo a algunos sectores.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Perjudica a alguien?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Toda decisión política tiene impacto social.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Qué dice sobre el medio ambiente?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Es un tema clave que no todos los candidatos priorizan.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Qué propone en derechos humanos y justicia social?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Algunos los defienden, otros los minimizan.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Qué pasó en los últimos años?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Hubo crisis, inflación, reformas. Eso influye en tu decisión.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Qué quiero mejorar?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Identificar tus prioridades te ayuda a decidir.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Cómo está la economía?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      La inflación, pobreza y desempleo son factores clave.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿El partido ya gobernó?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Podés evaluar su gestión pasada.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Me beneficiaría su gobierno?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Es válido pensar cómo impactará su gestión en tu vida.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Qué pasa si no voto?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Es obligatorio. Podés ser sancionado y, además, perdés voz.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Mi voto hace la diferencia?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Sí. Especialmente en elecciones reñidas.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Qué dicen los medios?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Escuchalos, pero también analizá por tu cuenta.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Voto por convicción o por miedo?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Lo ideal es votar por tus ideas, no por temor.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"faq-item\">\r\n");
      out.write("    <div class=\"faq-question\">\r\n");
      out.write("      ¿Estoy bien informado?\r\n");
      out.write("      <span class=\"arrow\">&#9660;</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faq-answer\">\r\n");
      out.write("      Evitá fake news. Informate por medios confiables.\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("    <h3>¿Cómo funciona esta plataforma?</h3>\r\n");
      out.write("    <p>Esta aplicación permite simular un proceso de elecciones en línea. Cada ciudadano registrado en el padrón puede emitir un voto válido en su distrito.</p>\r\n");
      out.write("    <p>Los administradores pueden gestionar candidatos, consultar resultados y monitorear la participación.</p>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <p style=\"font-size: 12px; color: #999;\">Proyecto desarrollado para fines educativos. &copy;GuzmanStudios todos los derechos reservados</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </p>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <script>\r\n");
      out.write("    document.querySelectorAll('.faq-item').forEach(item => {\r\n");
      out.write("  const question = item.querySelector('.faq-question');\r\n");
      out.write("  const answer = item.querySelector('.faq-answer');\r\n");
      out.write("  const arrow = item.querySelector('.arrow');\r\n");
      out.write("\r\n");
      out.write("  question.addEventListener('click', () => {\r\n");
      out.write("    const isOpen = answer.classList.contains('open');\r\n");
      out.write("\r\n");
      out.write("    // Cerrar todos\r\n");
      out.write("    document.querySelectorAll('.faq-answer.open').forEach(openAnswer => openAnswer.classList.remove('open'));\r\n");
      out.write("    document.querySelectorAll('.arrow.open').forEach(openArrow => openArrow.classList.remove('open'));\r\n");
      out.write("\r\n");
      out.write("    // Abrir solo si no estaba abierto\r\n");
      out.write("    if (!isOpen) {\r\n");
      out.write("      answer.classList.add('open');\r\n");
      out.write("      arrow.classList.add('open');\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("});\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
