/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-04-19 19:46:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.menu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menuForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t<meta charset=\"ISO-8859-1\">\n");
      out.write("\t<title>cac</title>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/jquery/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t\tvar contextPath='");
      out.print(request.getContextPath());
      out.write("';\n");
      out.write("\t</script>\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/menu-script.js\"> </script>\n");
      out.write("\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t\n");
      out.write("\t\t<div class=\"container mt-4\" >\n");
      out.write("\t\t\t\n");
      out.write("\t\t<h1>Menu</h1>\n");
      out.write("\t\t<form class=\"form\" id=\"#formPlato\">\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t    <label>Tipo de menu</label>\n");
      out.write("\t\t      <select id=\"inputState\" class=\"form-control\" id=\"cmbTipoMenu\">\n");
      out.write("\t\t        <option selected>Choose...</option>\n");
      out.write("\t\t        <option>Dia</option>\n");
      out.write("\t\t        <option>Estudiantil</option>\n");
      out.write("\t\t        <option>Ejecutivo</option>\n");
      out.write("\t\t      </select>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"form-group\" id=\"input-plato\">\n");
      out.write("\t\t    <label>Plato</label>\n");
      out.write("\t\t      <select  class=\"form-control\" id=\"cmbPlato\">\n");
      out.write("\t\t        <option selected>Choose...</option>\n");
      out.write("\t\t      </select>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"form-group\" id=\"input-postre\">\n");
      out.write("\t\t    <label>Postre</label>\n");
      out.write("\t\t      <select class=\"form-control\" id=\"cmbPostre\">\n");
      out.write("\t\t        <option selected>Choose...</option>\n");
      out.write("\t\t      </select>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"form-group\" id=\"input-bebida\">\n");
      out.write("\t\t    <label>Bebida</label>\n");
      out.write("\t\t      <select class=\"form-control\" id=\"cmbBebida\">\n");
      out.write("\t\t        <option selected>Choose...</option>\n");
      out.write("\t\t      </select>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t  <div class=\"form-group\">\n");
      out.write("\t\t    <label>Titulo</label>\n");
      out.write("\t\t    <input type=\"text\" class=\"form-control\" id=\"titulo\" name=\"titulo\" aria-describedby=\"emailHelp\" placeholder=\"Enter price\">\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t  <div class=\"form-group\">\n");
      out.write("\t\t    <label>Descripcion</label>\n");
      out.write("\t\t    <input type=\"text\" class=\"form-control\" id=\"descripcion\" name=\"descripcion\" placeholder=\"Enter description\">\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t  <div class=\"form-group\">\n");
      out.write("\t\t    <label>Precio</label>\n");
      out.write("\t\t    <input type=\"text\" class=\"form-control\" id=\"precio\" name=\"precio\" aria-describedby=\"emailHelp\" placeholder=\"Enter price\">\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t  <button type=\"button\" class=\"btn btn-primary\" id=\"btn-confirmar\">Submit</button>\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\t</form>\n");
      out.write("\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
