/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-04-16 19:05:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("\t<meta charset=\"ISO-8859-1\">\n");
      out.write("\t<title>sds\t</title>\n");
      out.write("\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/jquery/jquery.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t\tvar contextPath=\"");
      out.print(request.getContextPath());
      out.write("\";\n");
      out.write("\t</script>\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/scripts-barcito.js\"></script>\n");
      out.write("\t\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("\t<nav class=\"navbar navbar-light bg-light mt-4\">\n");
      out.write("\t  <a class=\"navbar-brand\" href=\"#\">Productos</a>\n");
      out.write("\t</nav>\n");
      out.write("\t<div class=\"card-group homeitem mt-4\" 1>\n");
      out.write("\t\t<div class=\"card m-2\" >\n");
      out.write("\t\t  <img class=\"card-img-top\" src=\"https://cdn.pixabay.com/photo/2023/05/31/11/15/fish-8031138_960_720.jpg\" alt=\"Card image cap\">\n");
      out.write("\t\t  <div class=\"card-body\">\n");
      out.write("\t\t    <h5 class=\"card-title\">Plato</h5>\n");
      out.write("\t\t    <p class=\"card-text\">Platos disponibles</p>\n");
      out.write("\t\t    <a href=\"");
      out.print( request.getContextPath());
      out.write("/LeerDatosPlato\" class=\"btn btn-primary\">Ir</a>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"card m-2\" >\n");
      out.write("\t\t  <img class=\"card-img-top\" src=\"https://cdn.pixabay.com/photo/2017/08/06/04/16/cupcake-2588646_1280.jpg\" alt=\"Card image cap\">\n");
      out.write("\t\t  <div class=\"card-body\">\n");
      out.write("\t\t    <h5 class=\"card-title\">Postres</h5>\n");
      out.write("\t\t    <p class=\"card-text\">postres disponibls</p>\n");
      out.write("\t\t    <a href=\"");
      out.print( request.getContextPath());
      out.write("/LeerDatosBebidas\" class=\"btn btn-primary\"  >Ir</a>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"card m-2\" >\n");
      out.write("\t\t  <img class=\"card-img-top\" src=\"https://cdn.pixabay.com/photo/2020/08/17/13/24/flower-5495384_1280.jpg\" alt=\"Card image cap\">\n");
      out.write("\t\t  <div class=\"card-body\">\n");
      out.write("\t\t    <h5 class=\"card-title\">Bebidas</h5>\n");
      out.write("\t\t    <p class=\"card-text\">Bebida disponible</p>\n");
      out.write("\t\t    <a href=\"");
      out.print( request.getContextPath());
      out.write("/LeerDatosBebidas\" class=\"btn btn-primary\">Ir</a>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"card m-2\" >\n");
      out.write("\t\t  <img class=\"card-img-top\" src=\"https://cdn.pixabay.com/photo/2016/11/29/12/54/cafe-1869656_1280.jpg\" alt=\"Card image cap\">\n");
      out.write("\t\t  <div class=\"card-body\">\n");
      out.write("\t\t    <h5 class=\"card-title\">Menu</h5>\n");
      out.write("\t\t    <p class=\"card-text\">menu disponibles</p>\n");
      out.write("\t\t    <a href=\"#\" class=\"btn btn-primary\">Ir</a>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<nav class=\"navbar navbar-light bg-light\">\n");
      out.write("\t  <a class=\"navbar-brand\" href=\"#\">Mesas</a>\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\t<div class=\"card-group homeitem mt-4\"  id=\"boxGroupMesas\">\n");
      out.write("\t\t<!-- \n");
      out.write("\t\t<div class=\"card m-2\" >\n");
      out.write("\t\t  <div class=\"card-body\">\n");
      out.write("\t\t    <h5 class=\"card-title\">Mesa 1</h5>\n");
      out.write("\t\t    <a href=\"#\" class=\"btn btn-primary\">Pedidos</a>\n");
      out.write("\t\t    <a href=\"#\" class=\"btn btn-danger\">Reservar</a>    \n");
      out.write("\t\t  </div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\n");
      out.write("\t\t<div class=\"card m-2\" >\n");
      out.write("\t\t  <div class=\"card-body\">\n");
      out.write("\t\t    <h5 class=\"card-title\">Mesa 2</h5>\n");
      out.write("\t\t    <a href=\"#\" class=\"btn btn-primary\">Pedidos</a>\n");
      out.write("\t\t    <a href=\"#\" class=\"btn btn-danger\">Reservar</a>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div class=\"card m-2\" >\n");
      out.write("\t\t\t  <div class=\"card-body\">\n");
      out.write("\t\t\t    <h5 class=\"card-title\">Mesa 3</h5>\n");
      out.write("\t\t\t    <a href=\"#\" class=\"btn btn-primary\">Pedidos</a>\n");
      out.write("\t\t\t    <a href=\"#\" class=\"btn btn-danger\">Reservar</a>  \n");
      out.write("\t\t\t  </div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"card m-2\" >\n");
      out.write("\t\t\t  <div class=\"card-body\">\n");
      out.write("\t\t\t    <h5 class=\"card-title\">Mesa 4</h5>\n");
      out.write("\t\t\t    <a href=\"#\" class=\"btn btn-primary\">Pedidos</a>\n");
      out.write("\t\t\t    <a href=\"#\" class=\"btn btn-danger\">Reservar</a>  \n");
      out.write("\t\t\t  </div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t -->\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
