/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-06-18 03:59:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menuElecciones_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("css/CssPadronElectoral.css\">\r\n");
      out.write("\t<link rel=\"icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/icon/icon.png\">\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>Elecciones</title>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var contextPath = \"");
      out.print(request.getContextPath());
      out.write("\";\r\n");
      out.write("    </script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/cargarDatosAdmin.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/scripts-barcito.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\"><header>\r\n");
      out.write("        <div class=\"titulo-pagina\">\r\n");
      out.write("            <h1>Menu Principal</h1>\r\n");
      out.write("            <p id=\"opacity\">Menu principal de la pagina</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"navbar\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/\" class=\"seleccionar\">Inicio</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/FAQ/FAQ.jsp\" class=\"seleccionar\">FAQ</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/seguridad/seguridad.jsp\" class=\"seleccionar\">Seguridad y Privacidad</a></li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"derecha\">\r\n");
      out.write("    <a href=\"#\" id=\"iniciarsesioncheck\"></a>\r\n");
      out.write("</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        \r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("            <div class=\"imagenfondo\"> \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t<div class=\"seleccion\">\r\n");
      out.write("\t\t<div class=\"card m-2\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"https://cloudfront-us-east-1.images.arcpublishing.com/infobae/PA5VI6NG75FA3MW5G4GSNWCY6Y.jpg\" alt=\"Card image cap\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Padron</h5>\r\n");
      out.write("\t\t\t\t<p class=\"card-text\">Ingresar al padron para votar</p>\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print( request.getContextPath());
      out.write("/Padron\" class=\"btn btn-primary\">Ir</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<div id=\"contenedorAdmin\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("</div>\r\n");
      out.write("        \r\n");
      out.write(" <section class=\"repetidor\">\r\n");
      out.write("        <div class=\"fila\">\r\n");
      out.write("            <div class=\"columna\"> \r\n");
      out.write("                \r\n");
      out.write("                <h2>Últimas novedades</h2>\r\n");
      out.write("    <ul style=\"list-style: none; padding: 0;\">\r\n");
      out.write("        <li>\r\n");
      out.write("            <strong>📅 12 de mayo:</strong> Se habilitó el simulador de votación digital para prácticas ciudadanas.\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <strong>🗳️ 5 de mayo:</strong> Nuevos candidatos cargados para las elecciones del distrito centro.\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <strong>📌 28 de abril:</strong> Cierre del padrón provisorio. Verificá tu inscripción.\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul></div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"columna\">\r\n");
      out.write("\r\n");
      out.write("                <h2>¿Cómo emitir tu voto?</h2>\r\n");
      out.write("   \r\n");
      out.write("        <li>Ingresá a la sección <strong>Padron</strong>.</li>\r\n");
      out.write("        <li>Colocá tu DNI y elegí tu mesa.</li>\r\n");
      out.write("        <li>Seleccioná los candidatos y confirmá tu voto.</li>\r\n");
      out.write("        <li>¡Listo! Tu voto será registrado y podrás ver los resultados.</li>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"fila\">\r\n");
      out.write("            <div class=\"columna\">\r\n");
      out.write("\r\n");
      out.write("                    <h2>¿Qué se vota en esta elección?</h2>\r\n");
      out.write("    <p>En esta simulación electoral se elige un representante por distrito entre los candidatos registrados. Cada distrito puede tener candidatos distintos y solo se permite un voto por ciudadano.</p>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"columna\">\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("    <h2>Contacto institucional</h2>\r\n");
      out.write("    <p>Ante cualquier duda o inconveniente, contactate con el equipo organizador de las elecciones escolares.</p>\r\n");
      out.write("    <p><strong>Email:</strong> elecciones@colegio.edu.ar</p>\r\n");
      out.write("    <p><strong>Teléfono:</strong> (011) 1234-5678</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"fila\">\r\n");
      out.write("            <div class=\"columna\">\r\n");
      out.write("                \r\n");
      out.write("                 <h3>Citas sobre democracia</h3>\r\n");
      out.write("    <p>“La democracia no es el silencio, es la claridad con que se exponen los problemas y la existencia de medios para resolverlos.” — Enrique Múgica</p>\r\n");
      out.write("    <p>“Votar es el derecho más básico y poderoso en una democracia.” — Barack Obama</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"columna\">\r\n");
      out.write("\r\n");
      out.write("                <h2>Preguntas frecuentes</h2>\r\n");
      out.write("    <p><strong>¿Puedo votar más de una vez?</strong><br>No. El sistema valida que cada ciudadano vote una sola vez.</p>\r\n");
      out.write("    <p><strong>¿Qué pasa si cierro la página mientras voto?</strong><br>Tu voto no será registrado hasta que confirmes la selección.</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("    <h3>¿Cómo funciona esta plataforma?</h3>\r\n");
      out.write("    <p>Esta aplicación permite simular un proceso de elecciones en línea. Cada ciudadano registrado en el padrón puede emitir un voto válido en su distrito.</p>\r\n");
      out.write("    <p>Los administradores pueden gestionar candidatos, consultar resultados y monitorear la participación.</p>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <p style=\"font-size: 12px; color: #999;\">Proyecto desarrollado para fines educativos. &copy;GuzmanStudios todos los derechos reservados</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </p>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
